//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("testTaskConfigurator.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ACTIONS {
            get {
                return ResourceManager.GetString("ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ADD_BUTTON {
            get {
                return ResourceManager.GetString("ADD_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question.
        /// </summary>
        public static string ADD_QUESTION_TITLE {
            get {
                return ResourceManager.GetString("ADD_QUESTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Configurator.
        /// </summary>
        public static string APPLICATION_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string ARABIC {
            get {
                return ResourceManager.GetString("ARABIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE_BUTTON {
            get {
                return ResourceManager.GetString("DELETE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this question?.
        /// </summary>
        public static string DELETE_CONFIRM_MESSAGE {
            get {
                return ResourceManager.GetString("DELETE_CONFIRM_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string DELETE_CONFIRM_TITLE {
            get {
                return ResourceManager.GetString("DELETE_CONFIRM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EDIT_BUTTON {
            get {
                return ResourceManager.GetString("EDIT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Caption.
        /// </summary>
        public static string END_CAPTION {
            get {
                return ResourceManager.GetString("END_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Value.
        /// </summary>
        public static string END_VALUE {
            get {
                return ResourceManager.GetString("END_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string ENGLISH {
            get {
                return ResourceManager.GetString("ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value must be greater than start value!.
        /// </summary>
        public static string ERROR_END_VALUE_LESS {
            get {
                return ResourceManager.GetString("ERROR_END_VALUE_LESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of smiley faces should be between 2 and 5.
        /// </summary>
        public static string ERROR_RANGE_SMILEY {
            get {
                return ResourceManager.GetString("ERROR_RANGE_SMILEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End caption is required !.
        /// </summary>
        public static string ERROR_REQUIRED_END_CAPTION {
            get {
                return ResourceManager.GetString("ERROR_REQUIRED_END_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value is required !.
        /// </summary>
        public static string ERROR_REQUIRED_END_VALUE {
            get {
                return ResourceManager.GetString("ERROR_REQUIRED_END_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question order is required !.
        /// </summary>
        public static string ERROR_REQUIRED_ORDER {
            get {
                return ResourceManager.GetString("ERROR_REQUIRED_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiley count is required !.
        /// </summary>
        public static string ERROR_REQUIRED_SMILEY_COUNT {
            get {
                return ResourceManager.GetString("ERROR_REQUIRED_SMILEY_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars count is required !.
        /// </summary>
        public static string ERROR_REQUIRED_STARS_COUNT {
            get {
                return ResourceManager.GetString("ERROR_REQUIRED_STARS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start caption is required !.
        /// </summary>
        public static string ERROR_REQUIRED_START_CAPTION {
            get {
                return ResourceManager.GetString("ERROR_REQUIRED_START_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value  is required !.
        /// </summary>
        public static string ERROR_REQUIRED_START_VALUE {
            get {
                return ResourceManager.GetString("ERROR_REQUIRED_START_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question text is required !.
        /// </summary>
        public static string ERROR_REQUIRED_TEXT {
            get {
                return ResourceManager.GetString("ERROR_REQUIRED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Type is required !.
        /// </summary>
        public static string ERROR_REQUIRED_TYPE {
            get {
                return ResourceManager.GetString("ERROR_REQUIRED_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value must be less than end value!.
        /// </summary>
        public static string ERROR_START_VALUE_GREATER {
            get {
                return ResourceManager.GetString("ERROR_START_VALUE_GREATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NEXT {
            get {
                return ResourceManager.GetString("NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Delete.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Order.
        /// </summary>
        public static string QUESTION_ORDER {
            get {
                return ResourceManager.GetString("QUESTION_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Text.
        /// </summary>
        public static string QUESTION_TEXT {
            get {
                return ResourceManager.GetString("QUESTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Type .
        /// </summary>
        public static string QUESTION_TYPE {
            get {
                return ResourceManager.GetString("QUESTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string QUESTIONS {
            get {
                return ResourceManager.GetString("QUESTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Question.
        /// </summary>
        public static string SLIDER_QUESTION {
            get {
                return ResourceManager.GetString("SLIDER_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider question info.
        /// </summary>
        public static string SLIDER_VIEW {
            get {
                return ResourceManager.GetString("SLIDER_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiley count.
        /// </summary>
        public static string SMILEY_COUNT {
            get {
                return ResourceManager.GetString("SMILEY_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiley Faces Question.
        /// </summary>
        public static string SMILEY_QUESTION {
            get {
                return ResourceManager.GetString("SMILEY_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiley faces question info.
        /// </summary>
        public static string SMILEY_VIEW {
            get {
                return ResourceManager.GetString("SMILEY_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars count.
        /// </summary>
        public static string STARS_COUNT {
            get {
                return ResourceManager.GetString("STARS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars Question.
        /// </summary>
        public static string STARS_QUESTION {
            get {
                return ResourceManager.GetString("STARS_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars question info.
        /// </summary>
        public static string STARS_VIEW {
            get {
                return ResourceManager.GetString("STARS_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Caption.
        /// </summary>
        public static string START_CAPTION {
            get {
                return ResourceManager.GetString("START_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Value.
        /// </summary>
        public static string START_VALUE {
            get {
                return ResourceManager.GetString("START_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string WRONG {
            get {
                return ResourceManager.GetString("WRONG", resourceCulture);
            }
        }
    }
}
