//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string COLUMN_ORDER {
            get {
                return ResourceManager.GetString("COLUMN_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Type.
        /// </summary>
        public static string COLUMN_QUESTION_TYPE {
            get {
                return ResourceManager.GetString("COLUMN_QUESTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string COLUMN_TEXT {
            get {
                return ResourceManager.GetString("COLUMN_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected question?.
        /// </summary>
        public static string CONFIRM_DELETE_MESSAGE {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string CONFIRM_DELETE_TITLE {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the database. Please check your server name, database name, username, and password..
        /// </summary>
        public static string ConnectionStringInvalid {
            get {
                return ResourceManager.GetString("ConnectionStringInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection string is not set or invalid. Go to Settings → Database Connection to set it up..
        /// </summary>
        public static string ConnectionStringNotSet {
            get {
                return ResourceManager.GetString("ConnectionStringNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the database. Contact the administrator to resolve the issue..
        /// </summary>
        public static string DatabaseConnectionFailed {
            get {
                return ResourceManager.GetString("DatabaseConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database could not be reached. It may be offline, deleted, or temporarily unavailable.  Please verify the database server and try again..
        /// </summary>
        public static string DatabaseUnavailable {
            get {
                return ResourceManager.GetString("DatabaseUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid caption. The caption text cannot be empty or longer than 30 characters ..
        /// </summary>
        public static string ERROR_CAPTION_TEXT_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_CAPTION_TEXT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid end value. It must be between {0} and {1} .
        /// </summary>
        public static string ERROR_END_VALUE_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("ERROR_END_VALUE_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid order value. The value must be non negative number ..
        /// </summary>
        public static string ERROR_ORDER_VALUE_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("ERROR_ORDER_VALUE_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid question. The question text cannot be empty or longer than 60 characters..
        /// </summary>
        public static string ERROR_QUESTION_TEXT_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_QUESTION_TEXT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid smiley count. The value must be between 2 and 5..
        /// </summary>
        public static string ERROR_SMILEY_COUNT_INVALID {
            get {
                return ResourceManager.GetString("ERROR_SMILEY_COUNT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid stars count. The value must be between 1 and 10..
        /// </summary>
        public static string ERROR_STARS_COUNT_INVALID {
            get {
                return ResourceManager.GetString("ERROR_STARS_COUNT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid start value. It must be between 0 and {0}.
        /// </summary>
        public static string ERROR_START_VALUE_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("ERROR_START_VALUE_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question not found..
        /// </summary>
        public static string NotFound_DeleteQuestion {
            get {
                return ResourceManager.GetString("NotFound_DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified question was not found. Please check your selection..
        /// </summary>
        public static string NotFound_EditQuestion {
            get {
                return ResourceManager.GetString("NotFound_EditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified question was not found. Please check your selection..
        /// </summary>
        public static string NotFound_GetQuestion {
            get {
                return ResourceManager.GetString("NotFound_GetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Question.
        /// </summary>
        public static string QUESTION_TYPE_SLIDER {
            get {
                return ResourceManager.GetString("QUESTION_TYPE_SLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiley Question.
        /// </summary>
        public static string QUESTION_TYPE_SMILEY {
            get {
                return ResourceManager.GetString("QUESTION_TYPE_SMILEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars Question.
        /// </summary>
        public static string QUESTION_TYPE_STARS {
            get {
                return ResourceManager.GetString("QUESTION_TYPE_STARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t save your question at the moment. Please try again later..
        /// </summary>
        public static string SqlErrorAddQuestion {
            get {
                return ResourceManager.GetString("SqlErrorAddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t delete your question at the moment. Please try again later..
        /// </summary>
        public static string SqlErrorDeleteQuestion {
            get {
                return ResourceManager.GetString("SqlErrorDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t update order at the moment. Please try again later..
        /// </summary>
        public static string SqlErrorEditOrder {
            get {
                return ResourceManager.GetString("SqlErrorEditOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t update your question at the moment. Please try again later..
        /// </summary>
        public static string SqlErrorEditQuestion {
            get {
                return ResourceManager.GetString("SqlErrorEditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t retrieve the question count at the moment. Please try again later..
        /// </summary>
        public static string SqlErrorGetCount {
            get {
                return ResourceManager.GetString("SqlErrorGetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t retrieve Last Modified. Please try again later..
        /// </summary>
        public static string SqlErrorGetLastModified {
            get {
                return ResourceManager.GetString("SqlErrorGetLastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t retrieve the question. Please try again later..
        /// </summary>
        public static string SqlErrorGetQuestion {
            get {
                return ResourceManager.GetString("SqlErrorGetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL error occurred while loading slider questions. Please contact support..
        /// </summary>
        public static string SqlErrorSliderLoad {
            get {
                return ResourceManager.GetString("SqlErrorSliderLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL error occurred while loading smiley questions. Please contact support..
        /// </summary>
        public static string SqlErrorSmileyLoad {
            get {
                return ResourceManager.GetString("SqlErrorSmileyLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL error occurred while loading star questions. Please contact support..
        /// </summary>
        public static string SqlErrorStarsLoad {
            get {
                return ResourceManager.GetString("SqlErrorStarsLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t update Last Modified. Please try again later..
        /// </summary>
        public static string SqlErrorUpdateLastModified {
            get {
                return ResourceManager.GetString("SqlErrorUpdateLastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please contact support or the system administrator..
        /// </summary>
        public static string UI_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("UI_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while adding question..
        /// </summary>
        public static string UnknownErrorAddQuestion {
            get {
                return ResourceManager.GetString("UnknownErrorAddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t change connection string due to an unexpected error. Please try again or contact support...
        /// </summary>
        public static string UnknownErrorChangeConnectionString {
            get {
                return ResourceManager.GetString("UnknownErrorChangeConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t test connection  due to an unexpected error. Please try again or contact support..
        /// </summary>
        public static string UnknownErrorConnectionTest {
            get {
                return ResourceManager.GetString("UnknownErrorConnectionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t delete your question due to an unexpected error. Please try again or contact support..
        /// </summary>
        public static string UnknownErrorDeleteQuestion {
            get {
                return ResourceManager.GetString("UnknownErrorDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t edit order due to an unexpected error.Please try again or contact support..
        /// </summary>
        public static string UnknownErrorEditOrder {
            get {
                return ResourceManager.GetString("UnknownErrorEditOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t edit question due to an unexpected error. Please try again or contact support..
        /// </summary>
        public static string UnknownErrorEditQuestion {
            get {
                return ResourceManager.GetString("UnknownErrorEditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t retrieve the connection string due to an unexpected error. Please try again or contact support..
        /// </summary>
        public static string UnknownErrorGetConnectionString {
            get {
                return ResourceManager.GetString("UnknownErrorGetConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t retrieve the question count due to an unexpected error. Please try again or contact support..
        /// </summary>
        public static string UnknownErrorGetCount {
            get {
                return ResourceManager.GetString("UnknownErrorGetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t retrieve Last Modified due to an unexpected error. Please try again or contact support..
        /// </summary>
        public static string UnknownErrorGetLastModified {
            get {
                return ResourceManager.GetString("UnknownErrorGetLastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t retrieve the question count due to an unexpected error. Please try again or contact support..
        /// </summary>
        public static string UnknownErrorGetQuestion {
            get {
                return ResourceManager.GetString("UnknownErrorGetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while loading questions..
        /// </summary>
        public static string UnknownErrorQuestionsLoad {
            get {
                return ResourceManager.GetString("UnknownErrorQuestionsLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while loading slider questions..
        /// </summary>
        public static string UnknownErrorSliderLoad {
            get {
                return ResourceManager.GetString("UnknownErrorSliderLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while loading smiley questions..
        /// </summary>
        public static string UnknownErrorSmileyLoad {
            get {
                return ResourceManager.GetString("UnknownErrorSmileyLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while loading star questions..
        /// </summary>
        public static string UnknownErrorStarsLoad {
            get {
                return ResourceManager.GetString("UnknownErrorStarsLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t update Last Modified due to an unexpected error. Please try again or contact support..
        /// </summary>
        public static string UnknownErrorUpdateLastModified {
            get {
                return ResourceManager.GetString("UnknownErrorUpdateLastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported question type..
        /// </summary>
        public static string UnsupportedQuestionType {
            get {
                return ResourceManager.GetString("UnsupportedQuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a question text or caption. This field cannot be empty..
        /// </summary>
        public static string Validation_EditQuestionDataNull {
            get {
                return ResourceManager.GetString("Validation_EditQuestionDataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order value must not be grater than number of question + 1 !. Please enter a valid number..
        /// </summary>
        public static string Validation_OrderOutOfRangeAdd {
            get {
                return ResourceManager.GetString("Validation_OrderOutOfRangeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order value must not be grater than number of question + 1 !. Please enter a valid number..
        /// </summary>
        public static string Validation_OrderOutOfRangeEdit {
            get {
                return ResourceManager.GetString("Validation_OrderOutOfRangeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a question text or caption. This field cannot be empty..
        /// </summary>
        public static string Validation_QuestionDataNull {
            get {
                return ResourceManager.GetString("Validation_QuestionDataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected question type is not valid. Please choose a supported type..
        /// </summary>
        public static string Validation_QuestionTypeInvalid {
            get {
                return ResourceManager.GetString("Validation_QuestionTypeInvalid", resourceCulture);
            }
        }
    }
}
